MONGODB_HOST: mongodb-{{ env }}.bmkrishtech.online
REDIS_HOST: redis-{{ env }}.bmkrishtech.online
MYSQL_HOST: mysql-{{ env }}.bmkrishtech.online 
RABBITMQ_HOST: rabbitmq-{{ env }}.bmkrishtech.online 
CATALOGUE_HOST: catalogue-{{ env }}.bmkrishtech.online
USER_HOST: user.bmkrishtech-{{ env }}.online
CART_HOST: cart.bmkrishtech-{{ env }}.online
SHIPPING_HOST: shipping-{{ env }}.bmkrishtech.online
PAYMENT_HOST: payment.bmkrishtech-{{ env }}.online